<?php
$countries = array(
	array("Afghanistan",			"AFG",	"Visa_requirements_for_Afghan_citizens"),
	array("Albania",				"ALB",	"Visa_requirements_for_Albanian_citizens"),
	array("Algeria",				"DZA",	"Visa_requirements_for_Algerian_citizens"),
	array("Angola",				"AGO",	"Visa_requirements_for_Angolan_citizens"),
	array("Argentina",			"ARG",	"Visa_requirements_for_Argentine_citizens"),
	array("Australia",			"AU1",	"Visa_requirements_for_Australian_citizens"),
	array("Austria",				"AUT",	"Visa_requirements_for_Austrian_citizens"),
	array("Azerbaijan",			"AZE",	"Visa_requirements_for_Azerbaijani_citizens"),
	array("Bangladesh",			"BGD",	"Visa_requirements_for_Bangladeshi_citizens"),
	array("Belgium",				"BEL",	"Visa_requirements_for_Belgian_citizens"),
	array("United Kingdom",		"GB1",	"Visa_requirements_for_British_citizens"),
	array("Brunei",				"BRN",	"Visa_requirements_for_Bruneian_citizens"),
	array("China",				"CH1",	"Visa_requirements_for_Chinese_citizens"),
	array("Republic of Congo",	"COG",	"Visa_requirements_for_Republic_of_the_Congo_citizens"),
	array("Croatia",				"HRV",	"Visa_requirements_for_Croatian_citizens"),
	array("Denmark",				"DN1",	"Visa_requirements_for_Danish_citizens"),
	array("Egypt",				"EGY",	"Visa_requirements_for_Egyptian_citizens"),
	array("Estonia",				"EST",	"Visa_requirements_for_Estonian_citizens"),
	array("Finland",				"FI1",	"Visa_requirements_for_Finnish_citizens"),
	array("France",				"FR1",	"Visa_requirements_for_French_citizens"),
	array("Germany",				"DEU",	"Travel_requirements_for_German_citizens"),
	array("Ghana",				"GHA",	"Visa_requirements_for_Ghanaian_citizens"),
	array("Guatemala",			"GTM",	"Visa_requirements_for_Guatemalan_citizens"),
	array("Hungary",				"HUN",	"Visa_requirements_for_Hungarian_citizens"),
	array("Iraq",				"IRQ",	"Visa_requirements_for_Iraqi_citizens"),
	array("Italy",				"ITA",	"Visa_requirements_for_Italian_citizens"),
	array("Japan",				"JPN",	"Visa_requirements_for_Japanese_citizens"),
	array("North Korea",			"PRK",	"Visa_requirements_for_North_Korean_citizens"),
	array("Kuwait",				"KWT",	"Visa_requirements_for_Kuwaiti_citizens"),
	array("Lebanon",				"LBN",	"Visa_requirements_for_Lebanese_citizens"),
	array("Malaysia",			"MYS",	"Visa_requirements_for_Malaysian_citizens"),
	array("Mexico",				"MEX",	"Visa_requirements_for_Mexican_citizens"),
	array("Moldova",				"MDA",	"Visa_requirements_for_Moldovan_citizens"),
	array("Mongolia",			"MNG",	"Visa_requirements_for_Mongolian_citizens"),
	array("Montenegro",			"MNE",	"Visa_requirements_for_Montenegrin_citizens"),
	array("Nepal",				"NPL",	"Visa_requirements_for_Nepalese_citizens"),
	array("Peru",				"PER",	"Visa_requirements_for_Peruvian_citizens"),
	array("Qatar",				"QAT",	"Visa_requirements_for_Qatari_citizens"),
	array("South Africa",		"ZAF",	"Visa_requirements_for_South_African_citizens"),
	array("Sweden",				"SWE",	"Visa_requirements_for_Swedish_citizens"),
	array("Turkey",				"TUR",	"Visa_requirements_for_Turkish_citizens"),
	array("Turkmenistan",		"TKM",	"Visa_requirements_for_Turkmen_citizens"),
	array("Tuvalu",				"TUV",	"Visa_requirements_for_Tuvaluan_citizens"),
	array("United Arab Emirates","ARE",	"Visa_requirements_for_Emirati_citizens"),
	array("United States of America","US1",	"Visa_requirements_for_United_States_citizens"),
	array("Vietnam",				"VNM",	"Visa_requirements_for_Vietnamese_citizens"),
	array("Yemen",				"YEM",	"Visa_requirements_for_Yemeni_citizens"),
	array("Swaziland",			"SWZ",	"Visa_requirements_for_Swazi_citizens"),
	array("Grenada",				"GRD",	"Visa_requirements_for_Grenadian_citizens"),
	array("New Zealand",			"NZ1",	"Visa_requirements_for_New_Zealand_citizens"),
	array("Poland",				"POL",	"Visa_requirements_for_Polish_citizens"),
	array("Belize",				"BLZ",	"Visa_requirements_for_Belizean_citizens"),
	array("Bolivia",				"BOL",	"Visa_requirements_for_Bolivian_citizens"),
	array("Botswana",			"BWA",	"Visa_requirements_for_Botswana_citizens"),
	array("Bulgaria",			"BGR",	"Visa_requirements_for_Bulgarian_citizens"),
	array("Burundi",				"BDI",	"Visa_requirements_for_Burundian_citizens"),
	array("Chile",				"CHL",	"Visa_requirements_for_Chilean_citizens"),
	array("Hong Kong",				"CH1",	"Visa_requirements_for_Chinese_citizens_of_Hong_Kong"),
	array("Macau",				"CH1",	"Visa_requirements_for_Chinese_citizens_of_Macau"),
	array("Democratic Republic of the Congo","COD",	"Visa_requirements_for_Democratic_Republic_of_the_Congo_citizens"),
	array("Costa Rica",			"CRI",	"Visa_requirements_for_Costa_Rican_citizens"),
	array("Cuba",				"CUB",	"Visa_requirements_for_Cuban_citizens"),
	array("Cyprus",				"CYP",	"Visa_requirements_for_Cypriot_citizens"),
	array("Dominica",			"DMA",	"Visa_requirements_for_Dominica_citizens"),
	array("Ecuador",				"ECU",	"Visa_requirements_for_Ecuadorian_citizens"),
	array("Netherlands",			"NL1",	"Visa_requirements_for_Dutch_citizens"),
	array("Eritrea",				"ERI",	"Visa_requirements_for_Eritrean_citizens"),
	array("Côte d'Ivoire",			"CIV",	"Visa_requirements_for_Ivorian_citizens"),
	array("Singapore",			"SGP",	"Visa_requirements_for_Singaporean_citizens"),
	array("The Bahamas",			"BHS",	"Visa_requirements_for_Bahamian_citizens"),
	array("Nauru",				"NRU",	"Visa_requirements_for_Nauruan_citizens"),
	array("Papua New Guinea",	"PNG",	"Visa_requirements_for_Papua_New_Guinean_citizens"),
	array("Solomon Islands",		"SLB",	"Visa_requirements_for_Solomon_Islands_citizens"),
	array("Samoa",				"WSM",	"Visa_requirements_for_Samoan_citizens"),
	array("Palau",				"PLW",	"Visa_requirements_for_Palauan_citizens"),
	array("Latvia",				"LVA",	"Visa_requirements_for_Latvian_citizens"),
	array("Luxembourg",			"LUX",	"Visa_requirements_for_citizens_of_Luxembourg"),
	array("Vanuatu",				"VUT",	"Visa_requirements_for_Vanuatuan_citizens"),
	array("Tonga",				"TON",	"Visa_requirements_for_Tongan_citizens"),
	array("Morocco",				"MAR",	"Visa_requirements_for_Moroccan_citizens"),
	array("Djibouti",			"DJI",	"Visa_requirements_for_Djiboutian_citizens"),
	array("Ethiopia",			"ETH",	"Visa_requirements_for_Ethiopian_citizens"),
	array("Mauritius",			"MUS",	"Visa_requirements_for_Mauritian_citizens"),
	array("United Republic of Tanzania",			"TZA",	"Visa_requirements_for_Tanzanian_citizens"),
	array("Portugal",			"PRT",	"Visa_requirements_for_Portuguese_citizens"),
	array("Iran",				"IRN",	"Visa_requirements_for_Iranian_citizens"),
	array("Switzerland",			"CHE",	"Visa_requirements_for_Swiss_citizens"),
	array("Syria",				"SYR",	"Visa_requirements_for_Syrian_citizens"),
	array("Saudi Arabia",		"SAU",	"Visa_requirements_for_Saudi_citizens"),
	array("Tunisia",				"TUN",	"Visa_requirements_for_Tunisian_citizens"),
	array("Bahrain",				"BHR",	"Visa_requirements_for_Bahraini_citizens"),
	array("Macedonia",			"MKD",	"Visa_requirements_for_citizens_of_North_Macedonia"),
	array("Honduras",			"HND",	"Visa_requirements_for_Honduran_citizens"),
	array("Iceland",				"ISL",	"Visa_requirements_for_Icelandic_citizens"),
	array("Venezuela",			"VEN",	"Visa_requirements_for_Venezuelan_citizens"),
	array("Ukraine",				"UKR",	"Visa_requirements_for_Ukrainian_citizens"),
	array("Spain",				"ESP",	"Visa_requirements_for_Spanish_citizens"),
	array("Panama",				"PAN",	"Visa_requirements_for_Panamanian_citizens"),
	array("Trinidad and Tobago",	"TTO",	"Visa_requirements_for_Trinidad_and_Tobago_citizens"),
	array("Georgia",				"GEO",	"Visa_requirements_for_Georgian_citizens"),
	array("Slovakia",			"SVK",	"Visa_requirements_for_Slovak_citizens"),
	array("Ireland",				"IRL",	"Visa_requirements_for_Irish_citizens"),
	array("Northern Cyprus",		"CYN",	"Visa_requirements_for_Northern_Cypriot_citizens"),
	array("India",				"IND",	"Visa_requirements_for_Indian_citizens"),
	array("Oman",				"OMN",	"Visa_requirements_for_Omani_citizens"),
	array("Greece",				"GRC",	"Visa_requirements_for_Greek_citizens"),
	array("Czech Republic",		"CZE",	"Visa_requirements_for_Czech_citizens"),
	array("Federated States of Micronesia","FSM",	"Visa_requirements_for_Micronesian_citizens"),
	array("Pakistan",			"PAK",	"Visa_requirements_for_Pakistani_citizens"),
	array("Barbados",			"BRB",	"Visa_requirements_for_Barbadian_citizens"),
	array("South Korea",			"KOR",	"Visa_requirements_for_South_Korean_citizens"),
	array("Marshall Islands",	"MHL",	"Visa_requirements_for_Marshall_Islands_citizens"),
	array("Indonesia",			"IDN",	"Visa_requirements_for_Indonesian_citizens"),
	array("Bosnia and Herzegovina","BIH",	"Visa_requirements_for_Bosnia_and_Herzegovina_citizens"),
	array("Canada",				"CAN",	"Visa_requirements_for_Canadian_citizens"),
	array("Israel",				"ISR",	"Visa_requirements_for_Israeli_citizens"),
	array("Brazil",				"BRA",	"Visa_requirements_for_Brazilian_citizens"),
	array("Colombia",			"COL",	"Visa_requirements_for_Colombian_citizens"),
	array("Russia",				"RUS",	"Visa_requirements_for_Russian_citizens"),
	array("Cameroon",			"CMR",	"Visa_requirements_for_Cameroonian_citizens"),
	array("Saint Lucia",			"LCA",	"Visa_requirements_for_Saint_Lucian_citizens"),
	array("Comoros",				"COM",	"Visa_requirements_for_Comorian_citizens"),
	array("Paraguay",			"PRY",	"Visa_requirements_for_Paraguayan_citizens"),
	// array("United Kingdom",		"GB1",	"Visa_requirements_for_British_Overseas_Citizens"),
	array("El Salvador",			"SLV",	"Visa_requirements_for_El_Salvador_citizens"),
	array("Maldives",			"MDV",	"Visa_requirements_for_Maldivian_citizens"),
	array("Nicaragua",			"NIC",	"Visa_requirements_for_Nicaraguan_citizens"),
	array("Namibia",				"NAM",	"Visa_requirements_for_Namibian_citizens"),
	array("Cambodia",			"KHM",	"Visa_requirements_for_Cambodian_citizens"),
	array("Laos",				"LAO",	"Visa_requirements_for_Laotian_citizens"),
	array("Romania",				"ROU",	"Visa_requirements_for_Romanian_citizens"),
	array("Uruguay",				"URY",	"Visa_requirements_for_Uruguayan_citizens"),
	array("Libya",				"LBY",	"Visa_requirements_for_Libyan_citizens"),
	array("Dominican Republic",	"DOM",	"Visa_requirements_for_Dominican_Republic_citizens"),
	array("Republic of Cabo Verde",			"CPV",	"Visa_requirements_for_Cape_Verdean_citizens"),
	array("Jordan",				"JOR",	"Visa_requirements_for_Jordanian_citizens"),
	// array("Italy",				"ITA",	"Visa_requirements_for_Sovereign_Military_Order_of_Malta"),
	array("Republic of Serbia",	"SRB",	"Visa_requirements_for_Serbian_citizens"),
	array("Slovenia",			"SVN",	"Visa_requirements_for_Slovenian_citizens"),
	array("Liechtenstein",		"LIE",	"Visa_requirements_for_Liechtenstein_citizens"),
	array("Uzbekistan",			"UZB",	"Visa_requirements_for_Uzbekistan_citizens"),
	array("Belarus",				"BLR",	"Visa_requirements_for_Belarusian_citizens"),
	array("Armenia",				"ARM",	"Visa_requirements_for_Armenian_citizens"),
	array("Taiwan",				"TWN",	"Visa_requirements_for_Taiwanese_citizens"),
	array("Zimbabwe",			"ZWE",	"Visa_requirements_for_Zimbabwean_citizens"),
	array("Sudan",				"SDN",	"Visa_requirements_for_Sudanese_citizens"),
	array("Palestine",				"ISR",	"Visa_requirements_for_Palestinian_citizens"),
	array("San Marino",			"SMR",	"Visa_requirements_for_Sammarinese_citizens"),
	array("Andorra",				"AND",	"Visa_requirements_for_Andorran_citizens"),
	array("Monaco",				"MCO",	"Visa_requirements_for_Monégasque_citizens"),
	array("Malta",				"MLT",	"Visa_requirements_for_Maltese_citizens"),
	array("Kazakhstan",			"KAZ",	"Visa_requirements_for_Kazakhstani_citizens"),
	// array("United Kingdom",		"GB1",	"Visa_requirements_for_British_Nationals_(Overseas)"),
	array("Philippines",			"PHL",	"Visa_requirements_for_Philippine_citizens"),
	array("Guyana",				"GUY",	"Visa_requirements_for_Guyanese_citizens"),
	array("Kenya",				"KEN",	"Visa_requirements_for_Kenyan_citizens"),
	// array("Latvia",				"LVA",	"Visa_requirements_for_Latvian_non-citizens"),
	// array("Estonia",				"EST",	"Visa_requirements_for_Estonian_non-citizens"),
	array("Saint Kitts and Nevis","KNA",	"Visa_requirements_for_Saint_Kitts_and_Nevis_citizens"),
	array("Tajikistan",			"TJK",	"Visa_requirements_for_Tajik_citizens"),
	array("Kyrgyzstan",			"KGZ",	"Visa_requirements_for_Kyrgyzstani_citizens"),
	array("Thailand",			"THA",	"Visa_requirements_for_Thai_citizens"),
	// array("United Kingdom",		"GB1",	"Visa_requirements_for_British_Overseas_Territories_Citizens"),
	array("Nigeria",				"NGA",	"Visa_requirements_for_Nigerian_citizens"),
	array("Haiti",				"HTI",	"Visa_requirements_for_Haitian_citizens"),
	array("Vatican",				"VAT",	"Visa_requirements_for_Vatican_citizens"),
	array("Lithuania",			"LTU",	"Visa_requirements_for_Lithuanian_citizens"),
	array("Sri Lanka",			"LKA",	"Visa_requirements_for_Sri_Lankan_citizens"),
	array("Bhutan",				"BTN",	"Visa_requirements_for_Bhutanese_citizens"),
	array("East Timor",			"TLS",	"Visa_requirements_for_East_Timorese_citizens"),
	array("Myanmar",				"MMR",	"Visa_requirements_for_Myanmar_citizens"),
	array("Seychelles",			"SYC",	"Visa_requirements_for_Seychellois_citizens"),
	array("Fiji",				"FJI",	"Visa_requirements_for_Fijian_citizens"),
	array("Jamaica",				"JAM",	"Visa_requirements_for_Jamaican_citizens"),
	array("Antigua and Barbuda",	"ATM",	"Visa_requirements_for_Antigua_and_Barbuda_citizens"),
	array("Mozambique",			"MOZ",	"Visa_requirements_for_Mozambican_citizens"),
	array("Norway",				"NOR",	"Visa_requirements_for_Norwegian_citizens"),
	array("Kosovo",				"KOS",	"Visa_requirements_for_Kosovan_citizens"),
	array("Malawi",				"MWI",	"Visa_requirements_for_Malawian_citizens"),
	array("Zambia",				"ZMB",	"Visa_requirements_for_Zambian_citizens"),
	array("Mauritania",				"MRT",	"Visa_requirements_for_Mauritanian_citizens"),
	array("Mali",				"MLI",	"Visa_requirements_for_Malian_citizens"),
	array("Senegal",				"SEN",	"Visa_requirements_for_Senegalese_citizens"),
	array("Guinea-Bissau",				"GNB",	"Visa_requirements_for_Guinea-Bissauan_citizens"),
	array("Guinea",				"GIN",	"Visa_requirements_for_Guinean_citizens"),
	array("Sierra Leone",				"SLE",	"Visa_requirements_for_Sierra_Leonean_citizens"),
	array("Liberia",				"LBR",	"Visa_requirements_for_Liberian_citizens"),
	array("Burkina Faso",				"BFA",	"Visa_requirements_for_Burkinabe_citizens"),
	array("Togo",				"TGO",	"Visa_requirements_for_Togolese_citizens"),
	array("Benin",				"BEN",	"Visa_requirements_for_Beninese_citizens"),
	array("Niger",				"NER",	"Visa_requirements_for_Nigerien_citizens"),
	array("Chad",				"TCD",	"Visa_requirements_for_Chadian_citizens"),
	array("Central African Republic",				"CAF",	"Visa_requirements_for_Central_African_Republic_citizens"),
	array("Equatorial Guinea",				"GNQ",	"Visa_requirements_for_Equatorial_Guinean_citizens"),
	array("The Gambia",				"GMB",	"Visa_requirements_for_Gambian_citizens"),
	array("Gabon",				"GAB",	"Visa_requirements_for_Gabonese_citizens"),
	array("South Sudan",				"SSD",	"Visa_requirements_for_South_Sudanese_citizens"),
	array("Uganda",				"UGA",	"Visa_requirements_for_Ugandan_citizens"),
	array("Rwanda",				"RWA",	"Visa_requirements_for_Rwandan_citizens"),
	array("Somalia",				"SOM",	"Visa_requirements_for_Somali_citizens"),
	array("Madagascar",				"MDG",	"Visa_requirements_for_Malagasy_citizens"),
	array("Suriname",				"SUR",	"Visa_requirements_for_Surinamese_citizens"),
	array("Saint Vincent and the Grenadines",				"VCT",	"Visa_requirements_for_Saint_Vincent_and_the_Grenadines_citizens"),
	array("Kiribati",				"KIR",	"Visa_requirements_for_Kiribati_citizens"),
	array("Lesotho",				"LSO",	"Visa_requirements_for_Lesotho_citizens"),
	array("Sao Tome and Principe",				"STP",	"Visa_requirements_for_Santomean_citizens"),

);
?>
